version = 0.1

[default]
[default.global.parameters]
stack_name = "journalm8-dev"

[default.deploy.parameters]
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
